name: Deploy to GitHub Pages
on: workflow_dispatch
env:
  RUSTUP_TERM_COLOR: always
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v5
      
      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown
      
      - name: Compile package
        run: cargo build --release
      
      - name: Create artifact
        run: |
          mkdir _site
          mv ./src/_config.yml _site/
          mv ./src/index.html _site/
          mv ./src/main.css _site/
          mv ./src/main.js _site/
          mv ./target/wasm32-unknown-unknown/release/chocoweb.wasm _site/
      
      - uses: actions/upload-pages-artifact@v4
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
